# Site settings
title: Beats & Deets | Wedding Planning Done Right
email: beatsanddeets@gmail.com
description: Wedding/event planning
baseurl: / # the subpath of your site, e.g. /blog/
url: beatsanddeets.com

#Permalink styles
permalink:           pretty
relative_permalinks: true

# Build settings
markdown: kramdown

exclude:
  - "bower_components"
  - "bower.json"

sass:
  sass_dir: _scss
  style: :compressed

jekyll-press:
  exclude: 'atom.xml'
  js_options: {}      # js minifier options
  css_options: {}     # css minifier options
  html_options: {}    # html minifier options