# Site settings
title: Beats & Deets | Wedding Planning Done Right
email: beatsanddeets@gmail.com
description: Wedding/event planning
baseurl: / # the subpath of your site, e.g. /blog/
url: http://BeatsAndDeets.Github.io/BeatsAndDeets
github:
  repo: https://github.com/BeatsAndDeets/BeatsAndDeets.git

#Permalink styles
permalink:           pretty
relative_permalinks: true

# Build settings
markdown: kramdown

exclude:
  - "bower_components"
  - "bower.json"

assets:
  sources:
    - _assets/javascript
    - _assets/stylesheets
    - _assets/images
  compress:
    css:  sass
    js:   uglifier
  cache:          true
  gzip: [ text/css, application/javascript ]