title: "Beats & Deets | Wedding Planning Done Right"
email: "beatsanddeets@gmail.com"
description: Wedding/event planning
baseurl: /BeatsAndDeets
url: http://BeatsAndDeets.Github.io/BeatsAndDeets
github:
  repo: "https://github.com/BeatsAndDeets/BeatsAndDeets.git"
permalink: pretty
relative_permalinks: true
gems: []
markdown: kramdown
exclude:
  - bower_components
  - bower.json
  - build
sass:
  sass_dir: _scss
  style: ":compressed"