# Site settings
title: Beats & Deets | Wedding Planning Done Right
email: beatsanddeets@gmail.com
description: Wedding/event planning
baseurl: / # the subpath of your site, e.g. /blog/
url: http://BeatsAndDeets.Github.io/BeatsAndDeets
github:
  repo: https://github.com/BeatsAndDeets/BeatsAndDeets.git

#Permalink styles
permalink:           pretty
relative_permalinks: true

# Include Gems
gems:      [bourbon, neat]

# Build settings
markdown: kramdown

exclude:
  - "bower_components"
  - "bower.json"
  - "build"

sass:
  sass_dir: _scss
  style: :compressed